export const CHANGE_CURRENT_SEARCH_PAGE = 'comicSearch/CHANGE_CURRENT_SEARCH_PAGE';
export const CHANGE_CURRENT_SEARCH_DATA = 'comicSearch/CHANGE_CURRENT_SEARCH_DATA';
export const CHANGE_CURRENT_SEARCH_TYPE = 'comicSearch/CHANGE_CURRENT_SEARCH_TYPE';
export const CHANGE_CURRENT_SEARCH_WORD = 'comicSearch/CHANGE_CURRENT_SEARCH_WORD';